# See https://github.com/MatadorProBr/revanced-extended-magisk-module/blob/main/CONFIG.md for more detailed explanations

compression-level = 9         # compression level for module zips. between 1 and 9
logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 3             # max number of concurrent building jobs
update-prebuilts = true       # dont touch this
build-mindetach-module = true


[YouTube-beta]
enabled = true                                                            # add 'enabled = false' key to entries to not build them
build-mode = "both"                                                       # 'both', 'apk' or 'module'
excluded-patches = "custom-branding-icon-afn-red custom-branding-name"    # whitespace seperated list of patches to exclude (multiline strings are not supported)
included-patches = "materialyou force-premium-heading"                    # whitespace seperated list of patches to include
version = "latest"                                                        # 'auto', 'auto' or a custom one like '17.40.41'
exclusive-patches = false                                                 # excludes all patches by default
microg-patch = "microg-support"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "ytrvx-magisk"
merge-integrations = true

[YouTube-blue-beta]
enabled = false
build-mode = "both"
excluded-patches = "custom-branding-icon-afn-red custom-branding-name"
included-patches = "custom-branding-icon-afn-blue materialyou force-premium-heading"
version = "latest"
exclusive-patches = false
microg-patch = "microg-support"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "ytrvx-magisk"
merge-integrations = true
rip-libs = true

[YouTube-red-beta]
enabled = false
build-mode = "both"
excluded-patches = "custom-branding-name"
included-patches = "materialyou force-premium-heading"
version = "latest"
exclusive-patches = false
microg-patch = "microg-support"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "ytrvx-magisk"
merge-integrations = true
rip-libs = true

[YouTube-revancify-beta]
enabled = false
build-mode = "both"
excluded-patches = "custom-branding-icon-afn-red custom-branding-name"
included-patches = "custom-branding-icon-revancify materialyou force-premium-heading"
version = "latest"
exclusive-patches = false
microg-patch = "microg-support"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "ytrvx-magisk"
merge-integrations = true
rip-libs = true

[Music-arm64]
build-mode = "both"
app-name = "Music"
excluded-patches = "custom-branding-music-red"
included-patches = ""
version = "auto"
microg-patch = "music-microg-support"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytmusicrvx-magisk"
merge-integrations = true
arch = "arm64-v8a"

[Music-arm64-red]
enabled = false
build-mode = "both"
app-name = "Music-red"
excluded-patches = ""
included-patches = ""
version = "auto"
microg-patch = "music-microg-support"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytmusicrvx-magisk"
merge-integrations = true
arch = "arm64-v8a"

[Music-arm64-blue]
enabled = false
build-mode = "both"
app-name = "Music-blue"
excluded-patches = "custom-branding-music-red"
included-patches = "custom-branding-music-revancify"
version = "auto"
microg-patch = "music-microg-support"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytmusicrvx-magisk"
merge-integrations = true
arch = "arm64-v8a"

[Music-arm]
build-mode = "both"
app-name = "Music"
excluded-patches = "custom-branding-music-red"
included-patches = ""
version = "auto"
microg-patch = "music-microg-support"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytmusicrvx-arm-magisk"
merge-integrations = true
arch = "arm-v7a"

[Music-arm-red]
enabled = false
build-mode = "both"
app-name = "Music-red"
excluded-patches = ""
included-patches = ""
version = "auto"
microg-patch = "music-microg-support"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytmusicrvx-magisk"
merge-integrations = true
arch = "arm-v7a"

[Music-arm-blue]
enabled = false
build-mode = "both"
app-name = "Music-blue"
excluded-patches = "custom-branding-music-red"
included-patches = "custom-branding-music-revancify"
version = "auto"
microg-patch = "music-microg-support"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytmusicrvx-magisk"
merge-integrations = true
arch = "arm-v7a"